# Description: W5: Load, SU, DM, SU
version: 1
id: wp5_load_su_dm_su_hudi
phases:
  - id: setup
    sessions:
      - tasks:
          - template_id: setup
  - id: setup_data_maintenance
    sessions:
      - tasks:
          - template_id: setup_data_maintenance
          - template_id: setup_data_maintenance
  - id: init
    sessions:
      - tasks:
          - template_id: init
  - id: build
    sessions:
      - tasks:
          - template_id: build
            replace_regex:
              - pattern: '(?i)varchar\(.*\)|char\(.*\)'
                replacement: 'string'
  - id: single_user_1
    sessions:
      - tasks:
          - template_id: single_user
  - id: data_maintenance_1
    sessions:
      - tasks:
          - template_id: data_maintenance_hudi
          - template_id: data_maintenance_hudi
  - id: single_user_2
    sessions:
      - tasks:
          - template_id: single_user